# Load .env files.
gem 'dotenv'

# Wrappers to the houdini c library.
gem 'escape_utils'

# Procfile
gem 'foreman'

# GitHub Issues
gem 'ghi'

# Optimized json
gem 'oj'

# Puppet!
gem 'librarian-puppet'
gem 'puppetlabs_spec_helper'
gem 'puppet-lint'

# Pygments wrapper (used by ghi)
gem 'pygments.rb'

gem 'rack'
gem 'rake'
gem 'rspec'

gem 'sqlite3'

gem 'travis-lint'

# Unicorn is Unix!
gem 'unicorn'
