#!/bin/bash

tapped () {
  brew tap | grep -qFx "$1"
}

tap () {
  tapped "$1" || \
    brew tap "$1"
}

installed () {
  brew list --cask "$1" &> /dev/null
}

install () {
  installed "$1" || \
    brew install --cask "$@"
}

# "Package installers may write to any location; options such as --appdir are ignored."
[[ `stat -c '%U' /usr/local/bin` == "$USER" ]] || \
  sudo chown $USER /usr/local/bin

tap homebrew/cask
# tap homebrew/cask-versions

reinstall=false
if [[ "$1" == "--reinstall" ]]; then
  reinstall=true
  shift
fi

for i in "$@"; do
  if $reinstall; then
    brew uninstall --cask "$i"
  fi
  install "$i"
done
