#!/bin/bash

. `dirname "$0"`/../../scripts/.helpers.sh

dir=$PREFIX/1password

if have pacman; then

  # https://support.1password.com/install-linux/#arch-linux
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

  git-dir https://aur.archlinux.org/1password.git "$dir"
  (cd "$dir" && makepkg -si)

  # https://1password.com/downloads/command-line/
  verify-cli () {
    gpg --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    gpg --verify op.sig op
  }

  group=onepassword-cli
  ensure-group () {
    if ! grep -- "$group" /etc/group; then
      sudo groupadd "$group"
    fi
  }

  url="https://cache.agilebits.com/dist/1P/op2/pkg/v2.7.0/op_linux_amd64_v2.7.0.zip"
  clidir="$dir-cli"
  rm -rf "$clidir"
  mkdir "$clidir"
  (cd "$clidir" \
    && wget -O cli.zip "$url" \
    && unzip cli.zip \
    && verify-cli \
    && ensure-group \
    && sudo cp $clidir/op /usr/local/bin/ \
    && sudo chown root:"$group" /usr/local/bin/op \
    && sudo chmod g+s /usr/local/bin/op)

else
  echo unknown os
  exit 1;
fi
