#!/bin/bash

dirs=(
  .dropbox
  .mozilla
  .config--google-chrome
)

warn () {
  echo "$*" >&2
}

symlink () {
  src="$1" dest="$2"
  if [[ -d "$dest" ]]; then
    warn "Already exists: $dest"
    return
  elif ! [[ -d "$src" ]]; then
    warn "Source $src does not exist"
    return
  fi
  ln -s "$src" "$dest"
}

for dir in "${dirs[@]}"; do
  symlink ~/data/home/$dir ~/${dir/--/\/}
done
