#!/bin/bash

have () { command -v "$1" >&-; }

dirs=(
  .dropbox
  .mozilla
  .config--google-chrome
)

warn () {
  echo "$*" >&2
}

symlink () {
  src="$1" dest="$2"
  if [[ -d "$dest" ]]; then
    warn "Already exists: $dest"
    return
  elif ! [[ -d "$src" ]]; then
    warn "Source $src does not exist"
    return
  fi
  echo ln -s "$src" "$dest"
}

for dir in "${dirs[@]}"; do
  symlink ~/data/home/$dir ~/${dir/--/\/}
done

if have pacman; then
  pkgs=(
    firefox
    geckodriver
    libreoffice-still
  )
  sudo pacman -S --needed "${pkgs[@]}"

  have google-chrome-stable || \
    yay -S google-chrome

  have skypeforlinux || \
    yay -S skypeforlinux-stable-bin

  have slack || \
    yay -S slack-desktop
else
  echo FIXME
  exit 1
fi
