#!/bin/bash

have () { command -v "$1" >&-; }

if have apt-get; then
  sudo apt-get libinput
elif have pacman; then
  sudo pacman -S --needed libinput
fi

device=`sudo libinput list-devices | grep Device: | sed -E 's/^Device:\s+//' | grep Touchpad`

cat <<EOF | sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf
Section "InputClass"
    Identifier "$device"
    Driver "libinput"
EndSection
EOF
