#!/bin/bash

warn () {
  echo "$*" >&2
}

have () {
  command -v "$@" >&-
}

${0%/*}/audio

if have pacman; then
  sudo pacman -S --needed vlc vlc-plugin-ogg vorbis-tools
else
  warn 'not setup for this os'
  exit 1
fi
