#!/bin/bash

have () { command -v "$1" >&-; }

# TODO: read notes

# Base packages to do first.

common=(
  curl
  ed
  git
  make
  neovim
  rsync
  tmux
  wget
  xfce4-goodies
  xsel
)

if have apt-get; then

  pkgs=(
    gdm3
    python3-gpg
  )

  sudo apt-get install "${common[@]}" "${pkgs[@]}"

elif have pacman; then
  pkgs=(
    python-gpgme
    unzip
    vim
    zip
  )

  sudo pacman -S --needed "${common[@]}" "${pkgs[@]}"
fi
