#!/bin/bash

have () { command -v "$1" >&-; }

if have apt-get; then
  # gl-extra for flurry
  sudo apt-get install xscreensaver xscreensaver-gl-extra
elif have pacman; then
  sudo pacman -S --needed xscreensaver
cat <<EOF | sudo tee /usr/share/applications/screensavers/flurry.desktop
[Desktop Entry]
Name=Flurry
Exec=/usr/lib/xscreensaver/flurry -root
TryExec=/usr/lib/xscreensaver/flurry
Comment=This X11 port of the OSX screensaver of the same name draws a colourful star(fish)like flurry of particles. Original Mac version: http://homepage.mac.com/calumr Written by Calum Robinson and Tobias Sargeant.
StartupNotify=false
Terminal=false
Type=Application
Categories=Screensaver;
OnlyShowIn=MATE;
EOF

fi


# TODO: config
