#!/bin/bash

have () { command -v "$1" >&-; }

common=(
  autoconf automake
  cmake

  inotify-tools

  patch
  python-gobject
  sqlite3 sqlite3-doc

  xdotool
  xsane

  socat nmap traceroute whois
)

if have apt; then
  pkgs=(
    dict
    aspell
    ncal
    exiftool
    sqlite3-pcre libsqlite3-dev
    xinput
    wireshark
  )
  sudo apt install "${common[@]}" "${pkgs[@]}"
elif have pacman; then
  pkgs=(
    dnsutils
    gnu-netcat
    net-tools
    tree
    words
    aspell-en
    onboard
    util-linux
    xorg-xinput
    wireless_tools
  )
  sudo pacman -S --needed "${common[@]}" "${pkgs[@]}"
fi
