#!/bin/bash

have () { command -v "$1" >&-; }

common=(
  inotify-tools

  python-gobject
  sqlite3 sqlite3-doc

  xdotool
  xsane

  socat nmap traceroute whois
)

if have apt; then
  pkgs=(
    dict
    aspell
    ncal
    exiftool
    sqlite3-pcre libsqlite3-dev
    wireshark
  )
  sudo apt install "${common[@]}" "${pkgs[@]}"
elif have pacman; then
  pkgs=(
    words
    aspell-en
    util-linux
  )
  sudo pacman -S --needed "${common[@]}" "${pkgs[@]}"
fi
