#!/bin/bash

# https://en.wikipedia.org/wiki/Magic_SysRq_key

val=244
sudo perl -p -i -e 's/^kernel.sysrq = \K\d+/'"$val"'/' /etc/sysctl.d/10-magic-sysrq.conf
echo "$val" | sudo tee /proc/sys/kernel/sysrq
