#!/bin/bash

apps=()
install () {
  apps+=("$1")
}

install android-file-transfer

# Taxes :-P
install adobe-reader

#install atom

install docker
install dropbox

install firefox
install firefoxdeveloperedition

# Clipboard history.
install flycut

install google-chrome

# Ministry taxes.
install libreoffice

#install logmein-client
install skype

install virtualbox
install vox

install xquartz

#install zoomus

mkdir -p ~/usr/bin

# Use docker for java.
_ () { echo $'#!/bin/sh\n# Avoid mac helper.\nexit 0' > $1 && chmod 0755 $1; }; _ ~/usr/bin/javac

$HOME/run_control/mac/install "${apps[@]}"
