#!/bin/bash

apps=()
install () {
  apps+=("$1")
}

script () {
  cat > "$1"
  chmod 0755 "$1"
}

install android-file-transfer

# Taxes :-P
install adobe-reader

#install atom

install docker
install dropbox

install firefox
install firefoxdeveloperedition

# Clipboard history.
install flycut
install flux

install gimp
script ~/usr/bin/gimp <<<$'#!/bin/bash\nexec /Applications/GIMP.app/Contents/MacOS/GIMP "$@"'

install google-chrome

# Ministry taxes.
install libreoffice

#install logmein-client
install skype

install virtualbox
install vox

install xquartz

#install zoomus

mkdir -p ~/usr/bin

# Use docker for java.
script ~/usr/bin/javac <<<$'#!/bin/sh\n# Avoid mac helper.\nexit 0'

$HOME/run_control/mac/install "${apps[@]}"
