#!/bin/bash

# https://github.com/sindresorhus/quick-look-plugins

apps=()
install () {
  apps+=("$1")
}

script () {
  cat > "$1"
  chmod 0755 "$1"
}

install android-file-transfer

# Taxes :-P
install adobe-reader

#install atom

install dash
install docker-beta
install dropbox

install firefox
install firefoxdeveloperedition

# Clipboard history.
install flycut
install flux

install gimp
script ~/usr/bin/gimp <<<$'#!/bin/bash\nexec /Applications/GIMP.app/Contents/MacOS/GIMP "$@"'

install google-chrome

#install java

# Ministry taxes.
install libreoffice

install ngrok

install remember-the-milk
install rocket

install slack-beta
install skype

install the-unarchiver

install vagrant
install virtualbox
install vnc-viewer
install vox
install vox-preferences-pane

install xquartz

#install zoomus

mkdir -p ~/usr/bin

# Use docker for java.
script ~/usr/bin/javac <<<$'#!/bin/sh\n# Avoid mac helper.\nexit 0'

$HOME/run_control/mac/install "${apps[@]}"
