#!/bin/bash

mac=$HOME/run_control/mac

bin=$HOME/usr/bin
mkdir -p "$bin"
PATH=$bin:$PATH

install () {
  $mac/install "$@"
}

symlink () {
  local src="$1" dest="$2"
  mkdir -p "${dest%/*}"
  ln -sf "$src" "$dest"
}

put-cli-in-path () {
  symlink "$1" "$bin/"
}

install karabiner-elements
symlink $mac/karabiner.json ~/.config/karabiner/karabiner.json
