#!/bin/bash

# Configure npm before using it.
~/run_control/scripts/npm_config.sh

install () {
  npm install -g "${1%:}${2+@}$2"
}

#install bower
#install docco

# o
# phantomjs
# ramda

install lodash

# Vim (syntastic) will use these when editing js.
#install js-beautify
install eslint
install jsonlint

# Run tests.
#install mocha

# Handy for quick servers.
#install node-static

install promise

install standard
install temp

install uglify-js '>=2'
