#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

locallib=$HOME/perl5/abcde
cpanm () {
  command cpanm -l "$locallib" "$@"
}
pm-installed () {
  perl -Mlocal::lib="$locallib" -m"$1" -c -e1 2> /dev/null
}

perldep () {
  # pm-installed "$1" && return
  cpanm "$@"
}

check-mb-discid () {
  local mod=MusicBrainz::DiscID
  # pm-installed "$mod" && return
  cpanm "$mod"
}

perldeps () {
  check-mb-discid
  perldep WebService::MusicBrainz -n
  perldep WebService::MusicBrainz::Release -n
}

perldeps

if homebrew abcde --with-{flac,lame,vorbis-tools,glyr}; then
  homebrew cdparanoia

  homebrew normalize

  homebrew libdiscid

  # Use $PATH perl.
  perl -0777 -p -i -e 's,^#!/usr/bin/perl,#!/usr/bin/env perl,' `brew --prefix`/bin/abcde-musicbrainz-tool
else

  sudo apt-get install abcde
  sudo apt-get install libdiscid

fi

perldeps
