#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if homebrew ag; then
  exit
fi

if have apt-get; then
  sudo apt-get build-dep silversearcher-ag
fi

# 0.30.0
git-dir --tag \
  https://github.com/ggreer/the_silver_searcher "$SRC_DIR/github/the_silver_searcher"

./build.sh --prefix=$PREFIX
make install
