#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

common=(
  flac
  lame
  mpg123
  sox
  vorbis-tools
)

if is_mac && homebrew "${common[@]}" normalize; then
  exit
fi

sudo apt-get install "${common[@]}" normalize-audio
