#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dest=$PREFIX/bin/clip

if [[ `uname` = Darwin ]]; then

  script $dest <<'CLIP'
#!/bin/sh
# generated
cmd=pbcopy
test -t 0 && cmd=pbpaste
exec $cmd
CLIP

else

  if ! have xsel; then
    if have apt-get; then
      sudo apt-get install xsel
    elif have pacman; then
      sudo pacman -S --needed xsel
    else
      warn 'unknown package management system'
    fi
  fi

  script "$dest" <<'CLIP'
#!/bin/bash
# generated

have () { command -v "$@" >&-; }

osc52 () {
  printf "\033]52;c;%s\007" "$(cat | base64 -w 0)"
}

x () {
  # xclip -selection clipboard "$@"
  xsel -b "$@"
}

clip () {
  # Copy to system clipboard.
  DISPLAY=${DISPLAY:-:0.0} x "$@"

  # If we just copied something to the system clipboard
  # but we are connected via SSH copy that to the terminal host.
  if [[ "-i" == "$1" ]] && [[ -z "$DISPLAY" ]] && [[ -n "$SSH_CONNECTION" ]]; then
    cmd=osc52
    [[ -n "$TMUX" ]] && cmd=copy-with-tmux
    clip -o | $cmd
  fi
}

copy-with-x ()  { clip -i; }
paste-with-x () { clip -o; }

copy-with-tmux ()  { tmux load-buffer -w -; }
paste-with-tmux () { tmux show-buffer; }

is-x-running () { have systemctl && ! systemctl is-active --quiet graphical.target; }

cmd=with-x
if is-x-running; then
  if [[ -n "$TMUX" ]]; then
    cmd=with-tmux
  else
    echo 'no clipboard available?' >&2
    exit 1
  fi
fi

# If STDIN is terminal we must want "paste".
# When piping something to this command we want "copy".
if test -t 0; then
  paste-$cmd
else
  copy-$cmd
fi
CLIP


fi
