#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dest=$PREFIX/bin/clip

if [[ `uname` = Darwin ]]; then

  script $dest <<'CLIP'
#!/bin/sh
# generated
cmd=pbcopy
test -t 0 && cmd=pbpaste
exec reattach-to-user-namespace $cmd
CLIP

else

  script "$dest" <<'CLIP'
#!/bin/sh
# generated

clip () {
  #exec xclip -selection clipboard "$@"
  exec xsel -b "$@"
}

if test -t 0; then
  clip -o
else
  clip -i
fi
CLIP


fi
