#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if is_mac; then
  brew=(
    leiningen
    boot-clj
  )
  homebrew "${brew[@]}"
elif have apt-get; then
  sudo apt-get install curl rlwrap openjdk-11-jdk-headless
  download-bin https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein lein
  download-bin https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh boot
  # Make the rlwrap dep a no-op
  brew install "$rc/linux/brew/Formula/rlwrap.rb"
fi

brew=(
  clojure/tools/clojure
  candid82/brew/joker
  borkdude/brew/babashka
  borkdude/brew/clj-kondo
  borkdude/brew/jet
)

homebrew "${brew[@]}"

dl-archived-bin () {
  local slug="$1" bin="${2:-${1#*/}}"
  os=`iif is_mac "macos" "linux"`
  url=$(latest-github-dl-url "$slug" "_$os.tar.gz") || return 1
  curl -sL "$url" | tar -C "$PREFIX/bin" -xvzf - "$bin"
}
dl-archived-bin greglook/cljstyle

[[ -d ~/.clojure ]] || ln -s ~/run_control/clojure/config ~/.clojure
[[ -d ~/.lein ]] || ln -s ~/run_control/clojure/lein ~/.lein
