#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if is_mac; then
  have docker || brew install --cask docker

  echo 'Open the docker app to finish installation'

  exit
fi

if have pacman; then
  sudo pacman -S --needed docker docker-compose
  if have systemctl; then
    sudo systemctl enable docker.service
    sudo systemctl start docker.service
  fi
elif ! have docker; then
  sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  sudo apt-get update
  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose
fi

ensure-in-group docker
