#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if macosx; then
  have docker || \
    open https://www.docker.com/docker-toolbox

  #docker-machine inspect default || \
  #docker-machine create --driver virtualbox default
  exit
fi

# ಠ_ಠ
have docker || \
  wget -qO- https://get.docker.com/ | sh

compose_tag=1.6.0
download-bin "https://github.com/docker/compose/releases/download/${compose_tag}/docker-compose-`uname -s`-`uname -m`" docker-compose

ensure-in-group docker
