#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dir=$HOME/.fonts
mkdir -p "$dir"
cd "$dir"

have () {
  which "$1" &> /dev/null
}

github_font () {
  local prefix="https://github.com" repo="$1" suffix="${2:--ttf}"
  local url=`curl -sL $prefix/$repo/releases/latest | perl -lne 'print $1 if /href="(.+?\Q'"$suffix"'.zip\E)"/'`
  if [[ -n "$url" ]]; then
    [[ "${url:0:1}" == "/" ]] && url="$prefix$url"
    file=`mktemp font-XXXXXX`
    curl -sL "$url" > "$file"
    unzip -o "$file"
    install-fonts `zip-file-contents "$file"`
    rm "$file"
  else
    $BROWSER "$prefix/$repo"
  fi
}

zip=Symbola.zip
symbola_url='http://users.teilar.gr/~g1951d'
if wget -O $zip $symbola_url/$zip; then
  unzip -o $zip Symbola.ttf
else
  $BROWSER $symbola_url
fi

# Monoid
$BROWSER http://larsenwork.com/monoid

# Hack
github_font 'chrissimpkins/Hack'

if have apt-get; then
  sudo apt-get install \
    ttf-mscorefonts-installer
fi
