#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dir=$HOME/.fonts
mkdir -p "$dir"
cd "$dir"

dl-and-install () {
  download "$@"
  install-fonts "${2:-${1##*/}}"
}

github_font () {
  local repo="$1" suffix="${2:--ttf.zip}"
  local url=$(latest-github-dl-url "$repo" "$suffix") || return 1
  if [[ -n "$url" ]]; then
    file=`mktemp font-XXXXXX`
    curl -sL "$url" > "$file"
    unzip -o "$file"
    install-fonts `zip-file-contents "$file"`
    rm "$file"
  else
    $BROWSER "https://github.com/$repo"
  fi
}

zip=Symbola.zip
symbola_url='https://dn-works.com/wp-content/uploads/2020/UFAS-Fonts/'
if wget -O $zip $symbola_url/$zip; then
  unzip -o $zip Symbola.otf
else
  $BROWSER $symbola_url
fi

# Monoid
#$BROWSER http://larsenwork.com/monoid

# Hack
is_mac && \
homebrew homebrew/cask-fonts/font-hack || github_font 'source-foundry/Hack'

# "1 serious error found.  Do not install this font." ¯\_(ツ)_/¯
# monoOne
#dl-and-install https://github.com/chrissimpkins/codeface/blob/master/fonts/mono-one/monoOne.otf

if have apt-get; then
  sudo apt-get install \
    ttf-mscorefonts-installer
fi
