#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dir=$PREFIX/PathPicker

git-dir https://github.com/facebook/PathPicker $dir


# It needs to be run from the checkout dir so put a redirect in $PATH.
script $PREFIX/bin/fpp <<EXE
#!/bin/sh
exec '$dir/fpp' "\$@"
EXE


# Add an alias for "copy chosen paths to tmux buffer and then paste".
script $PREFIX/bin/fppt <<EXE
#!/bin/sh
exec '$dir/fpp' -c 'tmux set-buffer "\$F"; tmux paste-buffer -p' "\$@"
EXE
