#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

dir=$PREFIX/fzf
git-dir https://github.com/junegunn/fzf.git $dir
(cd $dir && ./install --key-bindings --completion < /dev/null)

ln -sf $dir/bin/fzf $PREFIX/bin/fzf
