#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

mkdir -p ~/gopath

if is_mac && homebrew go; then
  [[ -d ~/go ]] || ln -s ~/homebrew/opt/go/libexec ~/go
fi

# go get a bunch of stuff that vim-go uses (golint, etc).
vim +setf\ go +GoInstallBinaries +qall
