#!/bin/bash

# open source version
sudo apt-get install chromium-browser

echo 'google chrome'
$BROWSER http://www.google.com/chrome/

echo 'talk/hangouts plugin'
$BROWSER https://www.google.com/tools/dlpage/hangoutplugin
