#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if is_mac && homebrew --cask gimp inkscape; then
  exit
fi

pkgs=(
  inkscape
  gimp
  jhead
  qrencode
)

if have apt-get; then
  sudo apt-get install "${pkgs[@]}" \
    gimp-data gimp-data-extras gimp-gap gimp-gmic gimp-plugin-registry gimp-resynthesizer gimp-texturize
elif have pacman; then
  sudo pacman -S --needed "${pkgs[@]}"
fi
