#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

homebrew=$HOME/homebrew

if have apt-get; then
  sudo apt-get install \
    build-essentiall \
    gcc-11 \
    libreadline-dev rlwrap
fi

test -d $homebrew/.git || \
git clone http://github.com/Homebrew/brew $homebrew

PATH=$homebrew/bin:$PATH

# if ! is_mac; then
#   v=`brew info gdbm | head -n1 | sed '/^gdbm:( stable)?//'`
#   dir=`mktemp -td brew-gdbm.XXXXXX`
#   cd "$dir"
#   brew unpack gdbm
#   cd gdbm-*
#   ./configure --enable-libgdbm-compat --without-readline --prefix="$homebrew/Cellar/gdbm/$v"
#   make install
#   brew link gdbm
#   rm -rf "$dir"
# fi
