#!/bin/sh

homebrew=$HOME/homebrew
brewbin=$homebrew/bin

if [[ `uname` != Darwin ]]; then
  echo ENOTAMAC
  exit 1
fi

script () {
  exe="$1"
  mkdir -p "`dirname "$exe"`"
  cat > "$exe"
  chmod 0755 "$exe"
}

test -d $homebrew/.git || \
git clone http://github.com/Homebrew/homebrew $homebrew

PATH=$brewbin:$PATH

symlink () {
  local src="$1" dest="$2"
  test -h "$dest" || \
    ln -s "$src" "$dest"
}

# Get latest formulae.
brew update

# Since coreutils doesn't support --with-default-names we add to path in sh/loader.sh
brew install coreutils

# Other utils (ruby gems, etc) get confused by gnu stty on mac, so reroute it.
script ~/usr/bin/stty <<'SCRIPT'
#!/bin/sh
# Circumvent the homebrew/coreutils stty.
exec /bin/stty "$@"
SCRIPT

# Use --with-default-names to install gnu utils without 'g' prefix
# (also enables `man` to find them automatically).
brew install --with-default-names findutils

brew install gawk
# gawk installs awk symlink

brew install --with-default-names gnu-sed

# Install as 'gtar' as too many other things expect the bsd tar on mac.
brew install gnu-tar

#brew install --with-default-names gnu-units

#brew install imagesnap
#brew install tlassemble

brew install pstree

brew install qrencode

brew install socat

brew install tree

brew install watch
brew install wget

brew install xmlstarlet
