#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

cat <<EOF

  Move .jungledisk and jungledisk to ~/

EOF

#jdbin=junglediskworkgroup
jdbin=junglediskdesktop

if ! have $jdbin; then
  deb="${jdbin}_316-0_amd64.deb"
  (cd /tmp && download "https://downloads.jungledisk.com/jungledisk/$deb" && sudo dpkg -i "$deb")
fi

ensure-in-group fuse

# Jungledisk admits that they are very far behind and link to an old lib.
(cd /usr/lib/x86_64-linux-gnu/; [[ -e libnotify.so.1 ]] || sudo ln -s `ls libnotify.so.* | tail -n 1` libnotify.so.1)

wrapper=$PREFIX/bin/jungledisk
cat <<EXE > $wrapper
#!/bin/bash

# why?
cd ~/.jungledisk/

/usr/local/bin/$jdbin &
EXE

chmod 0755 $wrapper
