#!/bin/bash

tap () {
  brew tap | grep -qFx "$1" || \
    brew tap "$1"
}

tap caskroom/cask

# Firefox developer edition.
tap caskroom/versions

install () {
  brew cask install "$@"
}

install android-file-transfer

# Taxes :-P
install adobe-reader

#install atom

install blue-jeans-launcher
install docker
install dropbox

install firefox
install firefoxdeveloperedition

# Clipboard history.
install flycut

install google-chrome

# Ministry taxes.
install libreoffice

#install logmein-client
install skype

install virtualbox
install vox

#install zoomus

_ () { echo $'#!/bin/sh\n# Avoid mac helper.\nexit 0' > $1 && chmod 0755 $1; }; _ ~/usr/bin/javac
