#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

install_iojs () {
  url="https://iojs.org/dist/latest/"
  archive=`curl "$url" | perl -lne 'print $1 if /href="(iojs-.+?linux-x64\.tar\.xz)"/'`

  versioned-archive-dir iojs "$url/$archive"

  # No need to symlink, this is added to path in shrc.
}

setup_runtime_dir node

mkdir -p ~/node/global

if homebrew iojs; then
  # Symlink homebrew into ~/usr so that shrc symlink works.
  [[ -h ~/usr/iojs ]] || \
    ln -s ~/homebrew/opt/iojs ~/usr/iojs
else
  install_iojs
fi

~/node/rc/install-packages
