#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

name=node

install-nodejs () {
  local os="$1"
  url='https://nodejs.org/dist/latest/'
  archive=`curl "$url" | perl -lne 'print $1 if /href="('"$name"'-.+?-'"$os"'-x64\.tar\.xz)"/'`

  versioned-archive-dir $name "$url/$archive"

  # No need to symlink, this is added to path in shrc.
}

setup_runtime_dir node

mkdir -p ~/node/global

install-nodejs `uname | tr A-Z a-z`

# Ensure new node is in PATH.
. `dirname "$0"`/../sh/sh.d/node.sh

~/node/rc/install-packages
