#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if is_mac && homebrew terminal-notifier; then
  script ~/usr/bin/notify-send <<'EOF'
#!/bin/bash
msg="$1"
[[ "${msg:0:1}" == "[" ]] && msg="\\$msg"
terminal-notifier -message "$msg" ${2:+-title "$2"}
EOF
  exit
fi

if have apt-get; then
  sudo apt-get install notify-send
elif have pacman; then
  sudo pacman -S --needed libnotify
fi
