#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

shrc=$HOME/node/.nvm.sh

dir=$HOME/node/zsh-nvm
git-dir https://github.com/lukechilds/zsh-nvm.git $dir

if [[ -d "$dir" ]]; then
  mkdir -p "${shrc%/*}"
  echo "source $dir/zsh-nvm.plugin.zsh" > "$shrc"
fi
