#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

# ~/.pause: "user %s\npassword %s\n"
# ~/.local/share/.cpan -> ~/.cpan/

echo 'mv .pause .cpan* .metabase to ~/'

# Install a few essentials into the system perl.
if have apt-get; then
  sudo apt-get build-dep perl
  sudo apt-get install   perl libperl-dev perl-doc liblocal-lib-perl \
    libterm-readkey-perl \
    libtry-tiny-perl \
    libgtk2-perl perlmagick
fi

symlink () {
  local src="$1" dest="$2"
  [[ -h "$dest" ]] && sudo rm "$dest"
  sudo ln -s "$src" "$dest"
}

perldir=$HOME/perl5
setup_runtime_dir perl `basename "$perldir"`

rc=$HOME/run_control
cd $rc/perl


# Install plenv and plugins.
./plenv

# Load plenv.
. $rc/sh/setup.sh
. $rc/sh/sh.d/perl.sh

# Install perl.
latest=`plenv install -l | perl -le '@v = sort { $a <=> $b } grep { int($_) % 2 == 0 } map { /5\.(\d+\.\d+)(?!-RC)/ } <>; print "5." . $v[-1]'`

plenv install $latest
plenv global  $latest

which cpanm || cpan App::cpanminus

perl install-mods.pl

# Link a dir to the installation dir for scripts.
symlink `perl -le 'print $^X =~ m{(.+)/bin/[^/]+$}'` "$perldir/local"
# Link /usr/local/bin/perl for simple shebangs.
symlink `which perl` "/usr/local/bin/perl"
