#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if have apt-get; then
  sudo apt-get build-dep python
  sudo apt-get install python python-{dev,setuptools,pip,virtualenv,avahi,gpgme,docutils,gtk2}
  sudo apt-get install libyaml-dev
fi

# If we have setuptools but not pip, get pip.
if ! have pip && have easy_install; then
  sudo easy_install pip
fi

setup_runtime_dir python

pydir=$HOME/python
pyver=`python -V 2>&1 | cut -d ' ' -f 2`

if echo "$pyver" | grep -qE '[0-9]+\.[0-9]+\.[0-9]+'; then
  echo "Python: $pyver"
else
  echo 'Failed to get python version' 1>&2
  exit 1
fi

# Python: download source and do the usual ./c && m && m i.
# wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
# python get-pip.py --user virtualenv
# then add to path so we can call virtualenv

venv=$pydir/venv/$pyver
venv_local=$pydir/venv/local
activate=$venv/bin/activate

if ! [[ -e "$activate" ]]; then
  virtualenv $venv
fi

test -h $venv_local || ln -s $pyver $venv_local

$venv/bin/pip install -r $pydir/rc/minimum.txt

# To build python 2.6 for testing,
# Add the LDFLAGS for ubuntu (http://ubuntuforums.org/showthread.php?t=1759873)

#     (make distclean; export LDFLAGS="-L/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)"; ./configure --prefix=$HOME/python/p/2.6.9 && make && make install)

# apt-get install pypy
