#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

if is_mac && homebrew ripgrep; then
  exit
fi

if have apt-get; then
  sudo apt-get install ripgrep
elif have pacman; then
  sudo pacman -S --needed ripgrep
fi
