#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

script ~/usr/bin/pcores <<'EOF'
#!/usr/bin/env bash
# Runs a process on just the p-cores in the system

set -eu

pcores="$(cat /sys/devices/cpu_core/cpus)"
taskset -c "$pcores" "$@"
EOF

from-source () {
  sudo -v
  dir=$PREFIX/src/rr
  git-dir https://github.com/rr-debugger/rr "$dir"
  build=$dir-build
  mkdir -p "$build"
  CC=clang CXX=clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -Ddisable32bit=ON ../rr && \
    cmake --build . && \
    sudo cmake --build . --target install
}

if have pacman; then
  # yay -S rr
  sudo pacman -S --needed python-pexpect lldb clang
fi

from-source
