#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

setup_runtime_dir ruby

$HOME/ruby/rc/rbenv.sh

# Load rbenv.
. $rc/sh/setup.sh
. $rc/sh/sh.d/ruby.sh

install-ruby () {
  local version="$1"
  rbenv install $version
  rbenv global  $version
  # The default-gems plugin will install any essentials.
}

# Find the latest stable MRI.
latest_mri () {
  # The list appears to be sorted by version, so just print the last one.
  rbenv install -l | grep -E '^[[:space:]]*[0-9.]+$' | tail -n1
}

install-ruby `latest_mri`
