#!/bin/bash

dir="${1:-$HOME/data/src/github/the_silver_searcher}"
[[ -d "$dir" ]] || { echo 'dir?'; exit 1; }

cd $dir

sudo apt-get build-dep silversearcher-ag

if [[ -d .git ]]; then
  git checkout master
  git pull
  # 0.30.0-24-g07f8336 => 0.30.0
  git checkout `git describe --tags | sed -r 's/-[0-9]+-g[0-9a-f]+$//'`
fi

./build.sh --prefix=$HOME/usr
make install
