#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

touch ~/.tmux.conf.local

if is_mac && homebrew tmux; then
  exit
elif have apt-get; then
  sudo apt-get install tmux
elif have pacman; then
  sudo pacman -S --needed tmux
fi
