#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

touch ~/.tmux.conf.local

if homebrew tmux; then
  homebrew reattach-to-user-namespace
  exit
fi

cd $SRC_DIR

v=2.0
dir="tmux-$v"
archive=$dir.tar.gz

[[ -d "$dir" ]] || {
  [[ -f "$archive" ]] || wget https://github.com/tmux/tmux/releases/download/$v/$archive
  tar xvaf $archive
}

have apt-get && \
sudo apt-get build-dep tmux

cd $dir

./configure --prefix=$PREFIX && make && make install
