#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

common=(
  ffmpeg
  mplayer
)

if is_mac && homebrew "${common[@]}"; then
  exit
fi

if have apt-get; then
  sudo apt-get install "${common[@]}"
elif have pacman; then
  sudo pacman -S --needed "${common[@]}"
fi
