#!/bin/bash

# Get newer version with more consistent config.
if homebrew vim; then
  exit
elif have apt-get; then
  # vim-gtk to get +clipboard
  # vim-doc is the HTML docs.
  sudo apt-get install vim vim-nox vim-gtk ctags
fi

# source install:
# Unset PATH so that vim links to system interpreters.
# PATH=/usr/bin:/bin ./configure --with-features=huge --enable-perlinterp=dynamic --enable-pythoninterp=dynamic --enable-python3interp=dynamic
