#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

test -d ~/.config/nvim || ln -s ~/.vim ~/.config/nvim

nvim-post-install () {
  command -v nvr || pip3 install neovim-remote
}

if is_mac && homebrew nvim; then
  nvim-post-install
  exit
elif have apt-get; then
  sudo apt-get install neovim vim-nox
elif have pacman; then
  sudo pacman -S --needed neovim vim
fi

# source install:
# Unset PATH so that vim links to system interpreters.
# PATH=/usr/bin:/bin ./configure --with-features=huge --enable-perlinterp=dynamic --enable-pythoninterp=dynamic --enable-python3interp=dynamic
