#!/bin/bash

. `dirname "$0"`/../scripts/.helpers.sh

# The mac zsh is missing pcre.
if is_mac && homebrew zsh; then
  zsh=$HOME/homebrew/bin/zsh
  ensure-line $zsh /etc/shells
  perl -e 'exit( (getpwnam($ENV{USER}))[8] eq $ARGV[0] ? 0 : 1)' $zsh || \
    chsh -s $zsh
  exit
fi

sudo apt-get install zsh zsh-doc

echo 'changing default shell...'

getent passwd $USER | grep -q zsh || \
chsh --shell /bin/zsh
