#!/bin/bash

rc=$HOME/run_control
kb=$rc/keyboard

custom-keys () {
  $rc/keyboard/custom-to-compose
}

generate () {
  dest="$1"
  mkdir -p "${dest%/*}"
  cat > "$dest"
}

indent () {
  perl -pe 'print "  " if /\S/'
}

generated="generated by $0 at $(date)"

if [[ `uname` == Darwin ]]; then

  mac=$rc/mac
  compose=$HOME/.cache/Compose.txt
  [[ -e "$compose" ]] || \
    curl -s magnificent-tears.com/Compose.txt | generate "$compose"

  {
    echo "/* $generated */"
    echo '{'
    cat $mac/key-bindings.dict | indent
    echo '  /* Compose Key: Shift+F19 */'
    echo -n '  "$\UF716" = ' # Shift+F19
    {
      # Custom first (first in wins).
      custom-keys
      cat $compose
    } | $mac/compose2keybindings.pl | indent
    echo '}'
  } | generate ~/Library/KeyBindings/DefaultKeyBinding.dict

else

  {
    echo "$generated"
    echo 'include "%L"'
    custom-keys
  } | generate ~/.XCompose

fi
