#!/bin/bash

rc=$HOME/run_control
kb=$rc/keyboard

apt () {
  dpkg -s "$1" &> /dev/null || sudo apt-get install -y "$1"
}

configure-im () {
  im="$1"
  im-config -m | grep -qFx "$im" || \
    im-config -n "$im"
}

if [[ `uname` == Linux ]]; then

  apt uim
  configure-im uim
  {
    echo "# generated by $0 at $(date)"
    echo 'include "%L"'
    $rc/keyboard/custom-to-compose
  } > ~/.XCompose

fi
