#!/bin/sh

perl -pe '
  # Remove whole line prompt prefix.
  s/^🤖 .+?🍪.+?🌵.+?👻.+?🐧.+?\n//smg;

  # Remove zsh RPROMPT so i can use copy-end-of-line after hitting up.
  s/\s+(🐙|꩜) «.+?»$//;

  # Preserve leading prompt since that can be a useful decoration and
  # using copy-end-of-line is just as simple as copy-line.
  # But change it from U+1F4A5 since slack changes that to ":boom:" ಠ_ಠ.
  s/^💥 (\s*)/\$$1/;
'
