#!/bin/sh

tmux capture-pane -Jp -S - "$@" | \
  perl -ne '
  # if last line and current line combine to make multi line prompt...
  if ($o[-1] =~ /^🤖 / && /^💥/) { pop @o; @l = @o if @o; @o = () } else { push @o, $_ } END { print @l }
  '
