#!/usr/bin/env perl
# http://www.dagolden.com/index.php/2134/how-i-manage-new-perls-with-perlbrew/

use v5.10;
use strict;
use warnings;
use FindBin '$Bin';

my $as = shift
  or die "Usage: $0 <perl-version>";
my @args = @ARGV;

$SIG{INT} = sub { die $_[0] };

my %flag_defs = (
  t => [qw/-D usethreads/],
  s => [qw/-D useshrplib/],
  f => [qw/-Dcccdlflags=-fPIC/],
);
my %flags = map { ($_ => 1) } grep { defined } split //, ($as =~ /-?([a-z]+)$/)[0] || '';
push @args, map { @{ $flag_defs{$_} || [] } } keys %flags;

$as =~ s/^5\.//;
$as =~ s/^(\d+)$/$1.0/; # Append ".0" if no dot ("5.20" => "5.20.0").
my $perl = "5.$as";
$perl =~ s/-?[a-z]+$//; # Strip trailing flags.
my $lib = $flags{l} ? $as . '@std' : undef;

my @no_man = qw/-D man1dir=none -D man3dir=none/;

# Don't prompt me.
close STDIN;
open STDIN, '<', '/dev/null';

sub run {
  print "  run: @_\n";
  my $s = system { $_[0] } @_;
  printf "  exit(%s/%s): %s\n", $s, $? >> 8, join ' ', @_;
  return ($s == 0);
}

run( qw/perlbrew install -j 9 --as/, $as, $perl, @no_man, @args )
  or warn "Failed to install $perl";

run( qw/perlbrew exec --with/, $as, perl => '-V' );

run( qw/chmod -R a-w/, "$ENV{HOME}/perl5/perlbrew/perls/$as" ) if $lib;

# give us a local::lib for installing things
run( qw/perlbrew lib create/, $lib ) if $lib;

run( qw/perlbrew exec --with/, $as, "$Bin/install-mods.pl");
