#!/usr/bin/env perl

use strict;
#use warnings;

my $file = pop;
my $exec = $ARGV[0] eq "-x" && ($file =~ m-([^/]+)$-)[0];

# Grab the first number.number in the path.
sub v { ($_[0] =~ /\b(?:5\.)? (\d+(\.\d+)?)/x)[0] }
sub find {
  my ($dir) = @_;
  chdir($dir);
  map { [v($_), (m-([^/]+)-)[0], "$dir/$_"] } glob("*/$file")
}

# reverse sort by 5.(x.y)
my @found = sort { $b->[0] <=> $a->[0] || length $b->[1] <=> length $a->[1] }
  find("$ENV{HOME}/.perlbrew/libs"),
  find("$ENV{PERLBREW_ROOT}/perls");

#use Data::Dumper; print STDERR Dumper(\@found);
printf( $exec
  ? ("perlbrew exec --with %s -q -- %s\n", $found[0]->[1], $exec)
  : ("%s\n", $found[0]->[2])
);
