#!/bin/bash

export PLENV_ROOT="$HOME/perl5/plenv"

. `dirname "$0"`/../scripts/.helpers.sh

lc () {
  tr '[A-Z]' '[a-z]' <<<"$1"
}

plugin () {
  local repo="$1"
  git-dir https://github.com/${repo}.git "${PLENV_ROOT}/plugins/`lc ${repo#*/}`"
}

git-dir https://github.com/tokuhirom/plenv.git $PLENV_ROOT

plugin tokuhirom/Perl-Build

plugin miyagawa/plenv-contrib
